/*
 * *************************************************************
 * PLEASE DO NOT EDIT THIS SCRIPT WITHOUT CONTACTING THE AUTHORS
 * *************************************************************
 * 
 * An enum of possible prop metadata.
 * This file is partially AUTOGENERATED by the TileManager program - do not edit manually!
 * 
 * AUTHORS:
 *  - Matt Filer
*/

/* Possible prop placement */
public enum PropPlacement
{
    INTERIOR,
    EXTERIOR,
}

/* Possible waypoint useage (should match PropParams in TileManager) */
public enum PropWaypointType
{
    NONE = -1,
    START = 0,
    MIDDLE = 1,
    END = 2,
}

/* POI types (should match PropParams in TileManager) */
public enum PoiType
{
    DEFAULT,
    INTERACTABLE,
    SITTABLE
}

/* Possible waypoint users (should match PropParams in TileManager) */
public enum PropWaypointUser
{
    NONE,
    GOONS, //Goons should really only use the END waypoint type (level exit)
    GOON_BATTLEBUS,
    FIRE_ENGINE,
    AMBULANCE,
}

/* Prop types (AUTO POPULATED - DO NOT EDIT) */
public enum PropTypes
{
    //**START_ENUMS**
VENDING_MACHINE = 0,
STEP_LADDERS = 1,
CHAIR = 2,
COMPUTER = 3,
BUCKET = 4,
DOORS = 5,
FIRE_PROP = 6,
INTERNAL_DOORS = 7,
BUS_STOP = 8,
TREE1 = 9,
LONG_TABLE = 16,
LOCKERS = 17,
WET_FLOOR_SIGN = 18,
PHOTOCOPIER = 19,
FIRE_EXTINGUISHER = 20,
}
