/*
 * *************************************************************
 * PLEASE DO NOT EDIT THIS SCRIPT WITHOUT CONTACTING THE AUTHORS
 * *************************************************************
 * 
 * An enum of possible tile metadata.
 * This file is partially AUTOGENERATED by the TileManager program - do not edit manually!
 * 
 * AUTHORS:
 *  - Matt Filer
*/

/* Tile use */
public enum TileUseage
{
    INTERIOR,
    EXTERIOR
}

/* Tile type */
public enum TileVariant
{
    WALL,
    FLOOR
}

/* Tile types (AUTO POPULATED) */
public enum TileTypes
{
    //**START_ENUMS**
BLUE_CARPET = 0, 
GREY_CARPET = 1, 
GRASS = 2, 
HIGH_WALL = 3, 
PATH_EXT = 4, 
PAVEMENT = 6, 
WOOD1 = 7, 
HIGH_WALL2 = 8, 
ROAD = 9, 
WOOD1_FLAMMABLE = 11, 
GREY_CARPET_FLAMMABLE = 12, 
BLUE_CARPET_FLAMMABLE = 13, 
PAVEMENT_PATH = 14, 
PAVEMENT_ROAD = 15, 
}
